spring.datasource.url=jdbc:sqlserver://localhost:1433;databaseName=EduSmartDB;encrypt=false
spring.datasource.username=sa
spring.datasource.password=Yancarlos12
spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.SQLServerDialect

server.port=8081